"""video and pictures added to article

Revision ID: 324b5cba85c4
Revises: 4bd40e1de96f
Create Date: 2019-12-03 19:56:55.023450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324b5cba85c4'
down_revision = '4bd40e1de96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('article', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'video')
    op.drop_column('article', 'picture')
    # ### end Alembic commands ###
