"""added log class

Revision ID: 38b030ca8029
Revises: 1a34b2eb1a37
Create Date: 2019-11-29 16:18:06.463257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b030ca8029'
down_revision = '1a34b2eb1a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.String(length=5), nullable=True),
    sa.Column('body', sa.String(length=240), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
